name: heartcare_plus
description: "A new Flutter project."

publish_to: 'none' 

environment:
  sdk: ^3.5.4

dependencies:
  intl: ^0.20.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Doctor.png